<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get employee by employee_id
     */
    function get_Employee($Employee_id)
    {
        return $this->db->get_where('Employee',array('Employee_id'=>$Employee_id))->row_array();
    }
       function get_Employee_id($Employee_name)
    {
        return $this->db->get_where('Employee',array('Employee_name'=>$Employee_name))->row_array();
    }
    /*
     * Get all Employee
     */
    function get_all_Employee()
    {
        $this->db->order_by('Employee_id', 'desc');
        return $this->db->get('Employee')->result_array();
    }

    /*
     * function to add new Employee
     */
    function add_Employee($params)
    {
        $this->db->insert('Employee',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update Employee
     */
    function update_Employee($Employee_id,$params)
    {
        $this->db->where('Employee_id',$Employee_id);
        return $this->db->update('Employee',$params);
    }

    /*
     * function to delete Employee
     */
    function delete_Employee($Employee_id)
    {
        return $this->db->delete('Employee',array('Employee_id'=>$Employee_id));
    }
}
